  import './globals.css'
  import { Inter, Montserrat, Alexandria, Syne } from 'next/font/google'
  import Header from '../components/Header';

  const inter = Inter({ subsets: ['latin'] })

  const montserrat = Montserrat({
    subsets: ['latin'],
    variable: '--font-montserrat',
    weight: ['100', '300', '400', '500', '600', '700', '800', '900'],
  });

  
  const alexandria = Alexandria({
    subsets: ['latin'],
    variable: '--font-alexandria',
    weight: ['100', '300', '400', '500', '600', '700', '800', '900'],
  });


  const syne = Syne({
    subsets: ['latin'],
    variable: '--font-syne',
    weight: ['400', '500', '600', '700', '800'],
  });

  export const metadata = {
    title: 'Brandlift Media',
    description: 'Generated by Brandlift Media',
  } 

  export default function RootLayout({ children }) {
    return (
      <html lang="en">
        <body className={`${inter.variable}  ${montserrat.variable}  ${alexandria.variable}  ${syne.variable}`}>
          <Header />
          {children}
        </body>
      </html>
    )
  }
